### ISSUE TITLE
Facebook Android SDK has upgraded to 4.0, this is a outdated example

### ISSUE THREAD

**Issue by Nevvea7** [firebase/firebase-login-demo-android#10]

**Comment by markbratanov** [comment]
Has anyone a working version with facebook sdk 4.0?

**Comment by markbratanov** [comment]
@Nevvea7 Would you have a working version with facebook sdk 4.0, or a link of one?

**Comment by Nevvea7** [comment]
@markbratanov Yeah, it's working in my project now. If you want I can write it in this login demo and send you a link or a pull request

**Comment by puf** [comment]
We just updated master to use Facebook SDK 4.1 (https://github.com/firebase/firebase-login-demo-android/pull/11)
