### ISSUE TITLE
Android Permissions

### ISSUE THREAD

**Issue by leedarrow** [firebase/firebase-login-demo-android#16]
I don't know if this is the appropriate way to go about this, but I'll mention it anyway.  This is really a suggestion.

 I am in the process of learning about Firebase via the online docs and this demo app, which is very good by the way.  Both are in fact.   I noticed that the app, unmodified by me, ends up requiring quite a view Android permissions.

```
INTERNET
USE_CREDENTIALS
GET_ACCOUNTS
ACCESS_NETWORK_STATE
WRITE_EXTERNAL_STORAGE
ACCESS_COURSE_LOCATION
READ_EXTERNAL_STORAGE
```

I noticed that it included the entire play-services package.  I experimented and was able to replace play-services with play-services-identity and play-services plus, like this:

```
//compile 'com.google.android.gms:play-services:7.5.0'
compile 'com.google.android.gms:play-services-identity:7.5.0'
compile 'com.google.android.gms:play-services-plus:7.5.0'
```

That reduced the required permissions to only the first three.  

It also reduced the overall package size, duhhh, but not significantly.  My personal opinion is that it's worth encouraging developers to use minimal permissions.

I should note that after this change, I did not actually run all the login flows to make sure they ran.  I'm assuming that since it compiles with only play-services-indentity and play-services-plus, and that since they know what permissions they require that it would run.

I did this test a week ago or so and I was going to write something nicer, but that task was falling off my plate so I thought I better get this in now, even without all the details.

Lee

**Comment by puf** [comment]
Hey Lee,

That looks like a great change. Can you turn it into a PR?

**Comment by leedarrow** [comment]
I intended to accomplish my first PR today (I use git both locally and with a shared team server, just not with a flow that uses push requests).  I thought the change itself was a slam dunk and that my real task was to figure out how to do a GitHub PR.

Turns out the change itself is a little more involved than I had expected.  Actually, it's not so much that the change is more complicated than I outlined in my OP, it's just that I can't get the Google login flow to work, and I didn't want to push anything that I didn't at least run first.

In working though this I realized that the original play-services version was 5.0.89 and the current play-services is 7.5.0.  I had forgotten that I had also changed the version number when I wrote my OP so I thought all I had changed was the specific play-services sub packages, but that's not true.  So that is the root of why it's more complicated than I had originally thought.

It also looks like there is some boilerplate play-services stuff left over from pre-7 (or it might be 6), which I'll update when I get it working on my system.

When I say I can't get it working, I'm not saying that it's anything wrong with the demo itself, it's just that I didn't get it working on my system in time today and I won't be able to get back to it for a few days.  My intention is to get it working and to submit a PR.

I hope that updating to play services 7.5.0 (or anything newer than 5.0.89) isn't an problem.  It was set to 5.0.89 10 months ago.  It was actually changed backwards to 5.0.89 to solve some sort of problem at the time.  But 10 months seems like a long time to stick with an old version of a library that has changed as much as the play services library does.  I'll guess that since it's a demo, being current is probably best.

**Comment by puf** [comment]
Hey Leedarrow,

Agreed: it would indeed be nice to stay up to date with other libraries. So if you still manage to get it working, just submit the PR and I'll work from that. I'll close this issue in the meantime. Just re-open it or create a new one if needed.

     Frank
