### ISSUE TITLE
How to clear Firebase authdata on Facebook App revoke?

### ISSUE THREAD

**Issue by ahetawal** [firebase/firebase-login-demo-android#17]
Hi All,
I am following the login with Facebook example for my app. I have a question regarding one of the login test cases as mentioned on facebook. Here is the scenario : 
1. First time user comes, sees the login to facebook button
2. Successfully logs in, sees and approves the facebook(fb) app permission screen, and I get the authdata, and some other info
3. User closes the app
4. User directly goes on Facebook and revokes the access to the fb app, approved in Step 2.
5. User opens the mobile app, and still able to use it, without getting the facebook login button..?

Ideally I would like to see the login button again.
Can you please help, how do we handle such a scenario with Firebase and Facebook together. Do I need to check something on every app restart and what all things i need to clear before new login starts?

Thanks again,

**Comment by puf** [comment]
Good question. Once a token has been granted, you cannot revoke that token. If you think this is a serious problem for your application, the best you can do is set a short Session Length in the Login & Auth tab of your App's dashboard.

If you have further questions, it might be better to post them on StackOverflow or the firebase-talk Google Group (https://groups.google.com/forum/#!forum/firebase-talk).
