### ISSUE TITLE
Update the example to ask for permission (required in Android M)

### ISSUE THREAD

**Issue by steren** [firebase/firebase-login-demo-android#19]
The sample project should be updated to request the GET_ACCOUNTS permission using Android M's requestPermissions().

See the official Google sample: https://github.com/googlesamples/google-services/blob/master/android/signin/app/src/main/java/com/google/samples/quickstart/signin/MainActivity.java

**Comment by deepakbhatia** [comment]
Yes I agree with this. I am trying to get it working. And having issues. Additionally updating it for  Play-services 8.3.0+

**Comment by puf** [comment]
To get Firebase authentication working with Google Play Services 8.3, have
a look at this StackOverflow question
<http://stackoverflow.com/questions/33631750/firebase-and-new-google-sign-in-on-android>.
Alternatively have a lookat our FirebaseUI-Android project
<https://github.com/firebase/FirebaseUI-Android>, which is likely to
replace this demo.
