### ISSUE TITLE
Update the example with latest G+ Sign in

### ISSUE THREAD

**Issue by YuryNazarchukCiklum** [firebase/firebase-login-demo-android#20]
Hello,
Recently Google add new library for G+ sign in. Could you please update application, docs could be find there:
https://developers.google.com/identity/sign-in/android/sign-in

**Comment by DariusL** [comment]
I'm trying to implement this right now. What scopes should we use to acquire token?

**Comment by puf** [comment]
I tested this and wrote up a [mini-answer to a question on StackOverflow]( http://stackoverflow.com/questions/33631750/firebase-and-new-google-sign-in-on-android/33662260#33662260). 

The scopes I use there: `oauth2:profile email`. I also tried with `oauth2:profile` and that seemed to work too.

**Comment by YuryNazarchukCiklum** [comment]
Thank you for quick response.
From your solution we need to reach google services twice and it's not an optimised solution. Will you update back end to accept id from Google Sign In:
    GoogleSignInAccount acct = result.getSignInAccount();
    String idToken = acct.getIdToken();
https://developers.google.com/identity/sign-in/android/backend-auth

**Comment by puf** [comment]
Thanks for the feedback. I'll relay that request to the engineering team. For the moment however, this approach is how it can be made to work. Closing.
