### ISSUE TITLE
Not able to configure Google Login

### ISSUE THREAD

**Issue by faisalmemon1991** [firebase/firebase-login-demo-android#22]
Facing this - 

Have added client id into firebase web app, when I run this project I see - 

`ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{5d3af3f: android.os.BinderProxy@441000c}, message=null}`

**Comment by puf** [comment]
Although the sign-in code in this project should still work, we are not actively maintaining it. For an up to date example of how to sign-in to Firebase with a Google account, see [FirebaseUI](https://github.com/firebase/FirebaseUI-Android)

**Comment by faisalmemon1991** [comment]
Will check. Thanks.
