### ISSUE TITLE
Google login permissions issue

### ISSUE THREAD

**Issue by gnardini** [firebase/firebase-login-demo-android#23]
Hi, I've been trying to integrate the google login with firebase to my app and just bumped into a permissions issue.

On the AsyncTask when trying to get the token, 
```java
 token = GoogleAuthUtil.getToken(
                            MainActivity.this,
                            Plus.AccountApi.getAccountName(mGoogleApiClient), scope);
```
I get the following error: 
`Caused by: java.lang.SecurityException: Missing android.permission.GET_ACCOUNTS`
I do have that permission on my manifest, but to make it work I need to manually ask for the permission on devices post API level 23.

On a side note, it would be nice if the updated flow supported using the updated sign in flow by Google, as suggested in the issue https://github.com/firebase/firebase-login-demo-android/issues/20

Cheers,

**Comment by puf** [comment]
We've stopped updating this app for new provider changes. Use or check [FirebaseUI](https://github.com/firebase/FirebaseUI-Android) for the most up to date Android authentication code.
