### ISSUE TITLE
Deprecated getToken in Play Services 8.4

### ISSUE THREAD

**Issue by Ioane5** [firebase/firebase-login-demo-android#24]
Hi!

I explored firebaseUI library which is more up to date but both versions use deprecated way of getting token. 

In this example you use:
``` Java
token = GoogleAuthUtil.getToken(GoogleOAuthActivity.this, Plus.AccountApi.getAccountName(mGoogleApiClient), scope);
``` 

In UI library it is:
``` Java
token = GoogleAuthUtil.getToken(mContext, emails[0], "oauth2:profile email");
```
 
Which is also deprecated. 

I tried to get and pass token as [google documentation](https://developers.google.com/identity/sign-in/android/backend-auth#send-the-id-token-to-your-server) says:

``` Java
    String idToken = acct.getIdToken();
```

But Firebase server always returned invalid credential error. 

How can I implement google sign in correctly? 

I don't want to use deprecated API, nevertheless it works. 

Thank you in advance

**Comment by puf** [comment]
For the latest sample of how to sign-in to Firebase with various providers, see [FirebaseUI](https://github.com/firebase/FirebaseUI-Android).

**Comment by Ioane5** [comment]
Maybe I wasn't clear enough. 

I want to use this method as it is stated in Firebase Documentation [here](https://www.firebase.com/docs/android/guide/login/google.html)

``` Java
Firebase ref = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
ref.authWithOAuthToken("google", "<OAuth Token>", new Firebase.AuthResultHandler() {
    @Override
    public void onAuthenticated(AuthData authData) {
        // the Google user is now authenticated with your Firebase app
    }

    @Override
    public void onAuthenticationError(FirebaseError firebaseError) {
        // there was an error
    }
});
```

But there is no way to get google plus `"<OAuth Token>"` without using deprecated API. 

As I explored FirebaseUI that you linked above, it also uses **deprecated** method ```String getToken (Context context, String accountName, String scope)``` for getting auth token. 

[Here](https://github.com/firebase/FirebaseUI-Android/blob/de3c357295d825cf17f0f4ce3470b2144d0087f3/library/src/main/java/com/firebase/ui/auth/google/GoogleOAuthTask.java#L25) on 25'th line in FirebaseUI core.

And see _[google documentation](https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil.html#public-methods)_ that marks this method as **deprecated**

I'm not using FirebaseUI, I'm doing it as It's in this demo. But the problem is that it's deprecated. 

Is there any other way to do it? 
I also checked [your answer](http://stackoverflow.com/a/33662260/4183017) on _stackoverflow_ and it's also uses deprecated method. 


I hope there is a good solution. 

Thanks!
