### ISSUE TITLE
Twitter Auth not working anymore

### ISSUE THREAD

**Issue by shrenuj** [firebase/firebase-login-demo-android#25]
After authenticating with twitter,the webview gives a 404 error containing the Auth token.The name,twitter id is returned,however the UID/Auth ID is not.

**Comment by abehaskins** [comment]
Hi,

This is a legacy sample which is no longer supported. Please check out the new [Firebase Auth](https://firebase.google.com/docs/auth/) and the samples on there!

Best,
abe
