### ISSUE TITLE
The lifecycle of the activity is not bounded to the callback

### ISSUE THREAD

**Issue by smith2310** [firebase/firebase-login-demo-android#8]
What happens if the callback gets called after the activity gets destroyed??

**Comment by jdimond** [comment]
The activity will not be destroyed since the callback will have a reference to it. A better implementation should remove the listener on an onStop call.

**Comment by smith2310** [comment]
Keeping a reference to the activity doesn't prevent the OS from destroying it. 
I agree with the remove listener part, but there's no way to remove or add a completion listener with the current api.

**Comment by jdimond** [comment]
What do you exactly mean with destroyed? The process might be killed (and with that the activity destroyed), the onDestroy method might be called, but as long as the process is alive, a reference will be kept for the activity (if it used in a callback and the callback has not fired yet).

I agree that there is no way to remove a completion listener with the current API. Completion listeners should be relatively short lived and (in most cases) not exceed the activity lifetime. You can also however add a completion listener that does not directly reference the activity. I agree though that this example does not do a good job of this.

Is there any specific callback you are talking about?

**Comment by smith2310** [comment]
In android an activity that has been stopped (send to the background through Home button or because another activity has been started) can be destroyed by the OS if the memory resources are needed. Of course, you can keep a reference to that activity even it has been destroyed but any attempts  to use it will lead to an exception. 

To solve this problem I had to create a wrapper service which is actually acts as the callback and the activity binds unbinds to this service during onResume and onPause, that way I can guarantee that response from the server (o error) will be saved and can be queried by the activity. The service can be destroyed as well but is 1000 times less likely than an activity. Does it make any sense?

P.D: IMO all this handling needs to be managed by the SDK itself through services like I did and BaseActivity classes

**Comment by jdimond** [comment]
Managing lifecycles by the SDK limits the flexibility on how the SDK can be used. There is also no need to use a service here. If you need access to Firebase data that exceeds the activity lifecycle (which can, but doesn't make sense in all cases), you can register listeners in the Application class or a singleton that is shared between activities (see e.g. [1]). If you need to make sure that the completion listener handles the case even after the activity was destroyed you can pass in a completion listener that is not bound to the activity lifecycle (i.e. not an anonymous inner class).

A service is appropriate when you want to ensure that Firebase data continues syncing when the application is in the background, which may, or may not make sense in your application.

[1] http://developer.android.com/reference/android/app/Application.html
