### ISSUE TITLE
GoogleOAuth Activity internal error

### ISSUE THREAD

**Issue by ersin-ertan** [firebase/firebase-login-demo-android#9]
A toast with "An internal error has occured" pops up after the screen goes semi dark.
This Toast is not in the code.

Logcat produces:
GoogleOAuth﹕ ConnectionResult{statusCode=SIGN_IN_REQUIRED, resolution=PendingIntent{41547f20: android.os.BinderProxy@41543778}}

Triggered by:
  @Override
   public void onConnectionFailed(ConnectionResult result){
	  if(! mGoogleIntentInProgress){
            /* Store the ConnectionResult so that we can use it later when the user clicks on the Google+ login button */
		 mGoogleConnectionResult = result;

		 if(mGoogleLoginClicked){
                /* The user has already clicked login so we attempt to resolve all errors until the user is signed in,
                 * or they cancel. */
			resolveSignInError();
		 }
		 else{
			Log.e(TAG, result.toString()); // <----- This log message
		 }
	  }
   }

USE_CREDETIALS permission is in the manifest.

**Comment by ersin-ertan** [comment]
Be sure to configure your application with google console and firebase security.

**Comment by VyMajoris** [comment]
Are you sure that your problem was configuration with the Google Console and the Firebase Login & Authentication?

I must be blind or something, because everything is OK on my end and it still giving me this error.

**Comment by ersin-ertan** [comment]
Yes as a checklist be sure to have(please add if I have missed a step(may not be in the correct order)):
1) Firebase User Login & Authentication Enable Google Authentication checked under the google tab.
2) Have a Google app
3) Generate Google Client ID
4) Plus api enabled in google console
5) Consent screen set google auth console
6) Use_credentials and a few permissions (be sure to have the google plus api permissions)
7) The generated sha 1 from the app in the google console generating a key to use in the app

**Comment by VyMajoris** [comment]
Well, something is happening here... Because everything checks.
http://i.imgur.com/chEylut.jpg

**Comment by jdimond** [comment]
Did you create a client ID for Android? Make sure to also activate deep linking. It can also take a couple of minutes until the application can use that client ID.

**Comment by VyMajoris** [comment]
Oh, I am sorry... I was indeed being blind. I was using the guide for web, not for Android!

**Comment by ShreyashPromact** [comment]
@VyMajoris  
is your issue get resolved? I am still getting same issue. All the things are configured well. I have also wait for couple of minutes for the client id as said by @jdimond  but still not get success. I am having same issue for google login.

**Comment by ShreyashPromact** [comment]
Sorry, Issue is resolved now. Actually there is guide problem in guide navigation which by default navigate to the Web App guide. I have just review the guide for android and configure it with proper details and now it is working fine.

Thanks.
